set(IC_ENGINE_VERSION_MAJOR 1)
set(IC_ENGINE_VERSION_MINOR 0)
set(IC_ENGINE_VERSION_PATCH 0)
set(IC_ENGINE_SOVERSION 1)
set(IC_ENGINE_VERSION_GITHASH 0)
set(IC_ENGINE_VERSION_NOTE "")

set(IC_ENGINE_VERSION
  ${IC_ENGINE_VERSION_MAJOR}.${IC_ENGINE_VERSION_MINOR}.${IC_ENGINE_VERSION_PATCH}
)